### ISSUE TITLE
Employment statuses, names and categories

### ISSUE THREAD

**Issue by zinob** [open-broker/specification#10]
Pretty much every bank has its own categories for employment statuses. This is a matrix of a few currently known categorizations. We need to be careful when choosing categories, and perhaps even more careful when choosing what to call them.

A                                     | B                      | C                       | D         
--                                     | --                      | --                       | --
Fast anställd   Permanent employment         | Tillsvidareanställning        | Permanent: fast                | PermantentlyEmployed  
Egen företagare Self-employed                | Egen företagare               | SelfEmployed: egen företagare  | OwnBusiness           
Vikariat        Temporary/Project employment | Tidsbegr anställning          | Temporary: vikariat/projekt    |                       
Timanställd     Temporary/Project employment | Tidsbegr anställning          | Temporary: vikariat/projekt    |                       
Projektanställd Temporary/Project employment | Tidsbegr anställning          | Temporary: vikariat/projekt    | ProjectEmployed       
Annat           Other                        | Annat                         | Unknown: Okänd                 | Other                 
Pensionär       Retired                      | Pensionär                     | Retired: pensionär             | RetiredAge            
Arbetslös       Un-employed                  | Arbetssökande                 | Unemployed: arbetslös          |                       
Studerande      Other                        | Studerande                    | Student: studerande            | Student               
Provanställd    Other                        |                               |                                |                       
.                                            | Sjuk och aktivitetsersättning |                                | RetiredIll            
.                                            | Utan förvärvsinkomst          |                                |

**Comment by williamhogman** [comment]
- `OTHER`  seems suitable
- `Student` could be used even if semantically a bit off
- `RetiredIllHealth` - seems useful

**Comment by williamhogman** [comment]
Anything else that ought to add?

**Comment by zinob** [comment]
Perhaps sickleave, but retired due to bad health is not very common technically not different from retired due to age

**Comment by williamhogman** [comment]
Well for some banks it is.

**Comment by williamhogman** [comment]
```
OTHER
FULL
TRIAL
RETIRED
HOURLY
EARLY_RETIRED
TEMPORARY
SELF_EMPLOYED
STUDENT
UNEMPLOYED
```
PROJECT --> temporary for clarity

**Comment by zinob** [comment]
Still there aren't many, there is little juridical difference and in worst case they can be discerned by birth-date.
