### ISSUE TITLE
Define application result-messages

### ISSUE THREAD

**Issue by zinob** [open-broker/specification#18]
The format in which the bank replies needs to be defined.
CloudEvents stringyness in number-types should help with the issue of weird binary rounding of APR. The event should at least contain:
- BrokerReference
- Outcome (accept, decline, manual_processing)
- Effective Interest Rate
- Nominal Interest Rate
- Offered Credit
- EstablishingFee
- TermFee
- NumberOfYears

**Comment by williamhogman** [comment]
Imho split accept, decline, manual into separate events.

**Comment by williamhogman** [comment]
```
MinAmount - minimum offer
MaxAmount - maximum offer
SomethingAmount - amount that the customer desired
```

**Comment by williamhogman** [comment]
EstablishingFee -> arrangementFee

**Comment by zinob** [comment]
Sure, 3 different types with possibly even more as defined by the bank is better than one type with to many meanings.
I did consider using Min And Max amount but since a minority of the banks provides that kind of data I thought that i might be better as an extension, a 0..1 ordinality might how ever be better?

**Comment by williamhogman** [comment]
`minAmount = maxAmount = offeredAmount` - Only one amount considered?

**Comment by zinob** [comment]
SomethingAmount -> ApprovedAmount: Normaly equal to the requested amount, this should also be the basis for the provided APR

**Comment by zinob** [comment]
> minAmount = maxAmount = offeredAmount - Only one amount considered?

Sure, the effect is the same.
