### ISSUE TITLE
Decide on Work/Home phone numbers

### ISSUE THREAD

**Issue by williamhogman** [open-broker/specification#6]
Should home and work phone numbers be included?

**Comment by williamhogman** [comment]
Moving to close, to close. Few people have home-phonenumbers in Sweden anymore.

@zinob

**Comment by zinob** [comment]
Work-phone might still be relevant. Most medical professions, some categories of guards and probably other are not allowed to carry personal cellphones during work-hours.

**Comment by williamhogman** [comment]
Ready to decide?

**Comment by zinob** [comment]
http://www.gp.se/nyheter/sverige/chefen-f%C3%A5r-f%C3%B6rbjuda-mobil-p%C3%A5-jobbet-och-i-skolan-1.5141112?noAccess=true&aId=1.5141112
We should probably have some support for additional numbers. SO a primary contact and a 0..* of additional phone numbers?
